// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            uuid.UUID          `json:"id"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	FirstName     *string            `json:"first_name"`
	LastName      *string            `json:"last_name"`
	Email         string             `json:"email"`
	Password      string             `json:"password"`
	Role          string             `json:"role"`
	EmailVerified bool               `json:"email_verified"`
}
